# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

alias(
    name = "com_api_example",
    actual = "//score/mw/com/example/com-api-example:com-api-example",
    visibility = ["//visibility:public"],
)

alias(
    name = "ipc_bridge_cpp",
    actual = "//score/mw/com/example/ipc_bridge:ipc_bridge_cpp",
    visibility = ["//visibility:public"],
)

alias(
    name = "ipc_bridge_rs",
    actual = "//score/mw/com/example/ipc_bridge:ipc_bridge_rs",
    visibility = ["//visibility:public"],
)

alias(
    name = "demo_server",
    actual = "//score/mw/com/example/systream_demo:demo_server",
    visibility = ["//visibility:public"],
)

alias(
    name = "demo_client",
    actual = "//score/mw/com/example/systream_demo:demo_client",
    visibility = ["//visibility:public"],
)
