# *******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Workflow configuration for S-CORE CI - Bazel Build & Test communication module
# This workflow runs Bazel test with enabled address, UB and leak sanitizer when triggered by specific pull request
# events.

name: Test communication module with address and UB and leak sanitizer
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request'}}
jobs:
    build_and_test_asan_ubsan_lsan:
      runs-on: ubuntu-24.04
      permissions:
        contents: read
      steps:
        - name: Checkout repository
          uses: actions/checkout@v6.0.2
        - name: Free Disk Space (Ubuntu)
          uses: eclipse-score/more-disk-space@v1
          with:
            level: 4
        - uses: bazel-contrib/setup-bazel@0.18.0
          with:
            bazelisk-cache: true
            disk-cache: "build_and_test_asan_ubsan_lsan"
            repository-cache: true
            cache-save: ${{ github.event_name == 'merge_group' }}
        - name: Allow linux-sandbox
          uses: ./actions/unblock_user_namespace_for_linux_sandbox
        - name: Bazel test communication targets with address and UB and leak sanitizer
          run: |
            bazel test --config=asan_ubsan_lsan //... --build_tests_only
